name: Run search bot

on:

  push:

  pull_request:

  schedule:

    - cron: "0 */2 * * *"

jobs:

  search:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node-version: [16.x]

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v2

        with:

          node-version: ${{ matrix.node-version }}

      - name: Install dependencies

        run: npm install

      - name: Run bot

        env:

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: node bot.js

